parameters:
#    arsoft_demo.example.class: ARSOFT\DemoBundle\Example

services:
#    arsoft_demo.example:
#        class: %arsoft_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
